### ISSUE TITLE
Following the docker instructions

### ISSUE THREAD

**Issue by AuspeXeu** [m0g/zeithub#41]
... causes this

![image](https://user-images.githubusercontent.com/2115696/68613201-39361680-048c-11ea-9216-91b8b9d23f4d.png)

**Comment by m0g** [comment]
Hello,

you need to import the run the database migration inside the docker container:

```
docker-compose exec zeithub npm run db:up
```

You might also need to pull the latest docker image (`docker-compose pull`).

I've also updated the readme

Cheers
